### ISSUE TITLE
You don't work in Florianópolis anymore

### ISSUE THREAD

**Issue by viniciuskneves** [danilowoz/danilowoz.github.io#1]
https://github.com/danilowoz/danilowoz.github.io/blob/master/index.html#L58

You're not working in my hometown anymore, please keep it up to date :rofl:

**Comment by viniciuskneves** [comment]
@danilowoz no you're not!

https://github.com/danilowoz/danilowoz.github.io/blob/master/index.html#L21

**Comment by danilowoz** [comment]
`dataLayer`? OMG???!

**Comment by danilowoz** [comment]
Moved to Porto 

![image](https://user-images.githubusercontent.com/4838076/50849490-19672b00-136f-11e9-95ca-037ef6597921.png)
